SpeedwayCenter/SpeedwayCenter/Areas/Admin/ViewModels/Rider/AdminAddRiderViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SpeedwayCenter.Areas.Admin.ViewModels.Rider
{
    public class AdminAddRiderViewModel
    {
        [Display(Name = "Name: ")]
        public string Name { get; set; }

        [Display(Name = "Forname: ")]
        public string Forname { get; set; }

        [Display(Name = "Birth Date: ")]
        [DisplayFormat(NullDisplayText = "")]
        public DateTime BirthDate { get; set; }

        [Display(Name = "Country: ")]
        public string Country { get; set; }

        [Display(Name = "Team: ")]
        public Guid TeamId { get; set; }
        public IEnumerable<AdminBasicInfoViewModel> Teams { get; set; }
    }
}

SpeedwayCenter/SpeedwayCenter/Areas/Admin/ViewModels/Rider/AdminEditRiderViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SpeedwayCenter.Areas.Admin.ViewModels.Rider
{
    public class AdminEditRiderViewModel
    {
        public Guid Id { get; set; }

        [Display(Name = "Name: ")]
        public string Name { get; set; }

        [Display(Name = "Forname: ")]
        public string Forname { get; set; }

        [Display(Name = "Birth Date: ")]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime BirthDate { get; set; }

        [Display(Name = "Country: ")]
        public string Country { get; set; }

        [Display(Name = "Team: ")]
        public Guid TeamId { get; set; }

        public IEnumerable<AdminBasicInfoViewModel> Teams { get; set; }
    }
}

SpeedwayCenter/SpeedwayCenter/Areas/Admin/ViewModels/Rider/AdminIndexRiderViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace SpeedwayCenter.Areas.Admin.ViewModels.Rider
{
    public class AdminIndexRiderViewModel
    {
        public Guid Id { get; set; }

        public string Name { get; set; }
        
        [Display(Name = "Birth Date")]
        [DisplayFormat(DataFormatString = "{0:d}")]
        public DateTime BirthDate { get; set; }
        
        public string Country { get; set; }
    }
}

SpeedwayCenter/SpeedwayCenter/ViewModels/Rider/HeatRiderViewModel.cs
using SpeedwayCenter.Interface.Enums;

namespace SpeedwayCenter.ViewModels.Rider
{
    public class HeatRiderViewModel
    {
        public string Name { get; set; }
        public int Score { get; set; }
    }
}

SpeedwayCenter/SpeedwayCenter/ViewModels/Rider/RiderDetailsViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SpeedwayCenter.ViewModels.Rider
{
    public class RiderDetailsViewModel
    {
        public string Name { get; set; }
        public string Country { get; set; }

        [Display(Name = "Birth Date")]
        public string BirthDate { get; set; }

        public BasicInfoViewModel Team { get; set; }
        public IList<RiderMatchViewModel> Matches { get; set; }
    }
}

SpeedwayCenter/SpeedwayCenter/ViewModels/Rider/RiderIndexViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace SpeedwayCenter.ViewModels.Rider
{
    public class RiderIndexViewModel
    {
        public Guid Id { get; }
        public string Name { get; } 

        [Display(Name = "Birth Date")]
        public string BirthDate { get; }

        public string Country { get; }

        public RiderIndexViewModel(Guid id, string name, string birthDate, string country)
        {
            Id = id;
            Name = name;
            BirthDate = birthDate;
            Country = country;
        }
    }
}

SpeedwayCenter/SpeedwayCenter/ViewModels/Rider/RiderMatchViewModel.cs
using System;

namespace SpeedwayCenter.ViewModels.Rider
{
    public class RiderMatchViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Date { get; set; }
        public string Score { get; set; }
        public string Points { get; set; }
        public int Total { get; set; }
    }
}

SpeedwayCenter/SpeedwayCenter/Areas/Admin/Controllers/RiderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SpeedwayCenter.Areas.Admin.ViewModels;
using SpeedwayCenter.Areas.Admin.ViewModels.Rider;
using SpeedwayCenter.ORM;
using SpeedwayCenter.ORM.Models;
using SpeedwayCenter.ORM.Repository;

namespace SpeedwayCenter.Areas.Admin.Controllers
{
    [Authorize]
    public class RiderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public RiderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ActionResult Index()
        {
            var riders = _unitOfWork.GetQueryRepository<Rider>();
            var records = riders.GetAll().ToList().Select(r => new AdminIndexRiderViewModel
            {
                Id = r.Id,
                Name = r.FullName,
                BirthDate = r.BirthDate,
                Country = r.Country
            });
            return View(records);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var teams = _unitOfWork.GetQueryRepository<Team>();
            var allTeams = GetTeamsList(teams);

            var viewModel = new AdminAddRiderViewModel
            {
                Teams = allTeams
            };
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(AdminAddRiderViewModel item)
        {
            var riders = _unitOfWork.GetRepository<Rider>();
            var teams = _unitOfWork.GetQueryRepository<Team>();

            var record = new Rider
            {
                Id = Guid.NewGuid(),
                Name = item.Name,
                Forname = item.Forname,
                BirthDate = item.BirthDate,
                Country = item.Country
            };

            if (item.TeamId != Guid.Empty)
            {
                var team = teams.FindBy(t => t.Id == item.TeamId);
                record.Teams = new List<Team>
                {
                    team
                };
            }

            riders.Add(record);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(Guid id)
        {
            var riders = _unitOfWork.GetRepository<Rider>();
            var record = riders.FindBy(r => r.Id == id);
            riders.Delete(record);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var riders = _unitOfWork.GetQueryRepository<Rider>();
            var teams = _unitOfWork.GetQueryRepository<Team>();
            var allTeams = GetTeamsList(teams);
            var rider = riders.FindBy(r => r.Id == id);
            var teamId = rider.Teams?
                //.Where(t =>
                //    t.Seasons.Any(s =>
                //        s.Name == "2016" &&
                //        s.League.Name == "Speedway Ekstraliga"))
                .Select(t => t.Id)
                .FirstOrDefault() ?? Guid.Empty;
            var viewModel = new AdminEditRiderViewModel
            {
                Id = rider.Id,
                Name = rider.Name,
                Forname = rider.Forname,
                BirthDate = rider.BirthDate,
                Country = rider.Country,
                Teams = allTeams,
                TeamId = teamId
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(AdminEditRiderViewModel item)
        {
            var riders = _unitOfWork.GetRepository<Rider>();
            var teams = _unitOfWork.GetQueryRepository<Team>();

            var record = riders.FindBy(r => r.Id == item.Id);

            record.Id = item.Id;
            record.Name = item.Name;
            record.Forname = item.Forname;
            record.BirthDate = item.BirthDate;
            record.Country = item.Country;

            if (item.TeamId != Guid.Empty)
            {
                var team = teams.FindBy(t => t.Id == item.TeamId);
                record.Teams = new List<Team>
                {
                    team
                };
            }
            else
            {
                record.Teams = null;
            }

            riders.Edit(record);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        private static IEnumerable<AdminBasicInfoViewModel> GetTeamsList(IQueryRepository<Team> teams)
        {
            var allTeams = teams.GetAll().Select(t => new AdminBasicInfoViewModel
            {
                Id = t.Id,
                Name = t.Name
            }).ToList();

            allTeams.Insert(0, new AdminBasicInfoViewModel
            {
                Id = Guid.Empty,
                Name = ""
            });

            return allTeams;
        }
    }
}

SpeedwayCenter/SpeedwayCenter/Controllers/RiderController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Imaging;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.UI.WebControls;
using Ninject.Infrastructure.Language;
using SpeedwayCenter.ORM.Models;
using SpeedwayCenter.ORM.Repository;
using SpeedwayCenter.ViewModels;
using SpeedwayCenter.ViewModels.Rider;

namespace SpeedwayCenter.Controllers
{
    public class RiderController : Controller
    {
        private readonly IQueryRepository<Rider> _repository;
        private const int Take = 10;

        public RiderController(IQueryRepository<Rider> repository)
        {
            _repository = repository;
        }

        public ActionResult Index(int page = 1, string searchValue = "")
        {
            var records = _repository
                .GetAll()
                .Select(r => new
                {
                    r.Id,
                    r.Name,
                    r.Forname,
                    r.BirthDate,
                    r.Country
                }).ToList();

            if (!string.IsNullOrEmpty(searchValue))
            {
                records = records
                    .Where(a => $"{a.Name} {a.Forname}".ToLower().Contains(searchValue.ToLower()))
                    .ToList();
            }

            var viewModel = records
                .Skip((page - 1) * Take)
                .Take(Take)
                .Select(r => new RiderIndexViewModel(
                    r.Id,
                    $"{r.Name} {r.Forname}",
                    r.BirthDate.ToShortDateString(),
                    r.Country))
                .ToEnumerable();

            ViewBag.NumberOfPages = (int)Math.Ceiling((decimal)records.Count / Take);
            ViewBag.Page = page;

            return View(viewModel);
        }

        public ViewResult Details(Guid id)
        {
            var rider = _repository.FindBy(r => r.Id == id);
            var team = rider.Teams.FirstOrDefault();

            BasicInfoViewModel viewModelTeam = null;

            if (team != null)
            {
                viewModelTeam = new BasicInfoViewModel
                {
                    Id = team.Id,
                    Name = team.FullName
                };
            }

            IList<RiderMatchViewModel> viewModelMatches = rider
                .HomeMeetings
                .Select(r => r.Match)
                .Concat(rider.AwayMeetings.Select(r => r.Match))
                .Select(m => new RiderMatchViewModel
                {
                    Id = m.Id,
                    Name = m.Name,
                    Date = m.Date?.ToShortDateString() ?? m.Status.ToString(),
                    Score = $"{m.HomeTeamPoints}:{m.AwayTeamPoints}",
                    Points = rider.GetPointsFromMeeting(m),
                    Total = rider.GetTotalPointsFromMeeting(m)
                }).ToList();

            var viewModel = new RiderDetailsViewModel
            {
                Name = rider.FullName,
                BirthDate = rider.BirthDate.ToShortDateString(),
                Country = rider.Country,
                Team = viewModelTeam,
                Matches = viewModelMatches
            };

            return View(viewModel);
        }
    }
}

SpeedwayCenter/SpeedwayCenter/Areas/Admin/Views/Rider/Add.cshtml
@using System.Web.Mvc.Html
@model SpeedwayCenter.Areas.Admin.ViewModels.Rider.AdminAddRiderViewModel
@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_AdminBasicLayout.cshtml";
}
<div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
    <h2>Add</h2>
    @using (@Html.BeginForm("Add", "Rider", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-sm-4 col-md-3" })
            <div class="col-sm-8 col-md-9">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Forname, new { @class = "control-label col-sm-4  col-md-3" })
            <div class="col-sm-8 col-md-9">
                @Html.TextBoxFor(model => model.Forname, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, new { @class = "control-label col-sm-4  col-md-3" })
            <div class="col-sm-8 col-md-9">
                @Html.TextBoxFor(model => model.BirthDate, new { @class = "form-control datepicker" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, new { @class = "control-label col-sm-4  col-md-3" })
            <div class="col-sm-8 col-md-9">
                @Html.TextBoxFor(model => model.Country, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeamId, new { @class = "control-label col-sm-4 col-md-3" })
            <div class="col-sm-8 col-md-9">
                @Html.DropDownListFor(model => model.TeamId, new SelectList(Model.Teams, "Id", "Name"), new { @class = "form-control" })
            </div>
        </div>
        <input type="submit" class="btn btn-default" value="Add" />
    }
</div>
<script type="text/javascript">
    $(function () {
        $(".datepicker").datepicker({
            startDate: '-100y',
            orientation: 'bottom'
        });
    });
</script>

SpeedwayCenter/SpeedwayCenter/Areas/Admin/Views/Rider/Edit.cshtml
@model SpeedwayCenter.Areas.Admin.ViewModels.Rider.AdminEditRiderViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminBasicLayout.cshtml";
}
<div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
    <h2>Edit</h2>
    @using (@Html.BeginForm("Edit", "Rider", FormMethod.Post, new { @class = "form-horizontal" }))
            {
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-sm-4 col-md-3" })
            <div class="col-sm-8 col-md-9">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Forname, new { @class = "control-label col-sm-4 col-md-3" })
            <div class="col-sm-8 col-md-9">
                @Html.EditorFor(model => model.Forname, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, new { @class = "control-label col-sm-4 col-md-3" })
            <div class="col-sm-8 col-md-9">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, new { @class = "control-label col-sm-4 col-md-3" })
            <div class="col-sm-8 col-md-9">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeamId, new { @class = "control-label col-sm-4 col-md-3" })
            <div class="col-sm-8 col-md-9">
                @Html.DropDownListFor(model => model.TeamId, new SelectList(Model.Teams, "Id", "Name", Model.TeamId), new { @class = "form-control" })
            </div>
        </div>

        @Html.HiddenFor(model => model.Id)
        <input type="submit" class="btn btn-default" value="Save" />
    }
</div>
<script type="text/javascript">
    $(function () {
        $(".datepicker").datepicker({
            startDate: '-100y',
            orientation: 'bottom'
        });
    });
</script>

SpeedwayCenter/SpeedwayCenter/Areas/Admin/Views/Rider/Index.cshtml
@model IEnumerable<SpeedwayCenter.Areas.Admin.ViewModels.Rider.AdminIndexRiderViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminBasicLayout.cshtml";
}

<h2>Rider</h2>

<table class="table table-hover">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>@Html.DisplayNameFor(model => model.Country)</th>
            <th>@Html.DisplayNameFor(model => model.BirthDate)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr data-href="@Url.Action("Edit", "Rider", new {Id = item.Id})">
                <td>@Html.DisplayFor(model => item.Name)</td>
                <td>@Html.DisplayFor(model => item.Country)</td>
                <td>@Html.DisplayFor(model => item.BirthDate)</td>
                <td>
                    @using (Html.BeginForm("Delete", "Rider", FormMethod.Post))
                    {
                        @Html.Hidden("id", item.Id)
                        <button type="submit" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span></button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
<a class="btn btn-success" href="@Url.Action("Add", "Rider")">Add</a>

<script>
    $('tr[data-href]').click(function () {
        window.location.href = $(this).data('href');
    });
</script>