SpeedwayCenter/SpeedwayCenter/Areas/Admin/ViewModels/Team/AdminAddTeamViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace SpeedwayCenter.Areas.Admin.ViewModels.Team
{
    public class AdminAddTeamViewModel
    {
        [Display(Name = "Name: ")]
        public string Name { get; set; }

        [Display(Name = "City: ")]
        public string City { get; set; }

        [Display(Name = "Stadium Name: ")]
        public string StadiumName { get; set; }

        [Display(Name = "Capacity: ")]
        public int Capacity { get; set; }
    }
}

SpeedwayCenter/SpeedwayCenter/Areas/Admin/ViewModels/Team/AdminEditRidersTeamViewModel.cs
using System;

namespace SpeedwayCenter.Areas.Admin.ViewModels.Team
{
    public class AdminEditRidersTeamViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }
}

SpeedwayCenter/SpeedwayCenter/Areas/Admin/ViewModels/Team/AdminEditTeamViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SpeedwayCenter.Areas.Admin.ViewModels.Team
{
    public class AdminEditTeamViewModel
    {
        public Guid Id { get; set; }

        [Display(Name = "Name: ")]
        public string Name { get; set; }

        [Display(Name = "City: ")]
        public string City { get; set; }

        [Display(Name = "Stadium Name: ")]
        public string StadiumName { get; set; }

        [Display(Name = "Capacity: ")]
        public int Capacity { get; set; }

        [Display(Name = "Riders: ")]
        public IEnumerable<AdminEditRidersTeamViewModel> Riders { get; set; }
    }
}

SpeedwayCenter/SpeedwayCenter/Areas/Admin/ViewModels/Team/AdminIndexTeamViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace SpeedwayCenter.Areas.Admin.ViewModels.Team
{
    public class AdminIndexTeamViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }

        [Display(Name = "Stadium Name")]
        public string StadiumName { get; set; }
        public int Capacity { get; set; }
    }
}

SpeedwayCenter/SpeedwayCenter/ViewModels/Team/TeamDetailsViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SpeedwayCenter.ViewModels.Team
{
    public class TeamDetailsViewModel
    {
        public string Name { get; set; }

        [Display(Name = "Stadium Name")]
        public string StadiumName { get; set; }

        public int Capacity { get; set; }

        public IEnumerable<BasicInfoViewModel> Riders { get; set; }
        public IEnumerable<TeamMatchViewModel> Matches { get; set; }
    }
}

SpeedwayCenter/SpeedwayCenter/ViewModels/Team/TeamIndexViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace SpeedwayCenter.ViewModels.Team
{
    public class TeamIndexViewModel
    {
        public Guid Id { get; }
        [Display(Name = "Name")]
        public string FullName { get; }

        [Display(Name = "Stadium Name")]
        public string StadiumName { get; }

        public int Capacity { get; }

        public TeamIndexViewModel(Guid id, string fullName, string stadiumName, int capacity)
        {
            Id = id;
            FullName = fullName;
            StadiumName = stadiumName;
            Capacity = capacity;
        }
    }
}

SpeedwayCenter/SpeedwayCenter/ViewModels/Team/TeamMatchViewModel.cs
using System;

namespace SpeedwayCenter.ViewModels.Team
{
    public class TeamMatchViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Date { get; set; }
        public string Score { get; set; }
    }
}

SpeedwayCenter/SpeedwayCenter/Areas/Admin/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SpeedwayCenter.Areas.Admin.ViewModels.Rider;
using SpeedwayCenter.Areas.Admin.ViewModels.Team;
using SpeedwayCenter.ORM;
using SpeedwayCenter.ORM.Models;

namespace SpeedwayCenter.Areas.Admin.Controllers
{
    [Authorize]
    public class TeamController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public TeamController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ActionResult Index()
        {
            var teams = _unitOfWork.GetQueryRepository<Team>();
            var records = teams.GetAll().ToList().Select(r => new AdminIndexTeamViewModel
            {
                Id = r.Id,
                Name = $"{r.Name} {r.City}",
                StadiumName = r.StadiumName,
                Capacity = r.Capacity
            });
            return View(records);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(AdminAddTeamViewModel item)
        {
            var teams = _unitOfWork.GetRepository<Team>();
            var seasons = _unitOfWork.GetQueryRepository<Season>();
            var thisSeason = seasons.FindBy(s => s.Name == "2016");

            var record = new Team
            {
                Id = Guid.NewGuid(),
                Name = item.Name,
                City = item.City,
                StadiumName = item.StadiumName,
                Capacity = item.Capacity,
                Seasons = new List<Season> { thisSeason }
            };

            teams.Add(record);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(Guid id)
        {
            var teams = _unitOfWork.GetRepository<Team>();
            var record = teams.FindBy(r => r.Id == id);
            teams.Delete(record);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var teams = _unitOfWork.GetQueryRepository<Team>();
            var records = teams.FindBy(r => r.Id == id);
            var viewModel = new AdminEditTeamViewModel
            {
                Id = records.Id,
                Name = records.Name,
                City = records.City,
                StadiumName = records.StadiumName,
                Capacity = records.Capacity,
                Riders = records.Riders?.Select(r => new AdminEditRidersTeamViewModel
                {
                    Id = r.Id,
                    Name = $"{r.Name} {r.Forname}"
                })
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(AdminEditTeamViewModel item)
        {
            var teams = _unitOfWork.GetRepository<Team>();
            var record = teams.FindBy(t => t.Id == item.Id);

            if (record == null)
            {
                record = new Team();
            }

            record.Id = item.Id;
            record.Name = item.Name;
            record.City = item.City;
            record.StadiumName = item.StadiumName;
            record.Capacity = item.Capacity;

            teams.Edit(record);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }
    }
}

SpeedwayCenter/SpeedwayCenter/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpeedwayCenter.ORM.Models;
using SpeedwayCenter.ORM.Repository;
using SpeedwayCenter.ViewModels;
using SpeedwayCenter.ViewModels.Table;
using SpeedwayCenter.ViewModels.Team;

namespace SpeedwayCenter.Controllers
{
    public class TeamController : Controller
    {
        private readonly IQueryRepository<Team> _queryRepository;
        private const int Take = 10;

        public TeamController(IQueryRepository<Team> queryRepository)
        {
            _queryRepository = queryRepository;
        }

        public ActionResult Index(int page = 1, string searchValue = "")
        {
            var records = _queryRepository
                .GetAll()
                .ToList();

            if (!string.IsNullOrEmpty(searchValue))
            {
                records = records
                    .Where(a => $"{a.Name} {a.City}".ToLower().Contains(searchValue.ToLower()))
                    .ToList();
            }

            var viewModel = records
                .Skip((page - 1) * Take)
                .Take(Take)
                .Select(t => new TeamIndexViewModel(
                    t.Id,
                    $"{t.FullName}",
                    t.StadiumName,
                    t.Capacity));

            ViewBag.NumberOfPages = (int)Math.Ceiling((decimal)records.Count / Take);
            ViewBag.Page = page;

            return View(viewModel);
        }

        public ViewResult Details(Guid id)
        {
            var team = _queryRepository.FindBy(t => t.Id == id);

            var riders = team.Riders.Select(r => new BasicInfoViewModel
            {
                Id = r.Id,
                Name = r.FullName
            });

            var matches = team.AllMeetings.Select(m => new TeamMatchViewModel
            {
                Id = m.Id,
                Name = m.Name,
                Score = $"{m.HomeTeamPoints}:{m.AwayTeamPoints}",
                Date = m.Date?.ToShortDateString() ?? m.Status.ToString()
            });

            var viewModel = new TeamDetailsViewModel
            {
                Name = team.Name,
                StadiumName = team.StadiumName,
                Capacity = team.Capacity,
                Riders = riders,
                Matches = matches
            };

            return View(viewModel);
        }
    }
}

SpeedwayCenter/SpeedwayCenter/Areas/Admin/Views/Team/Add.cshtml
@model SpeedwayCenter.Areas.Admin.ViewModels.Team.AdminAddTeamViewModel
@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_AdminBasicLayout.cshtml";
}
<div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
    <h2>Add</h2>
    @using (@Html.BeginForm("Add", "Team", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-sm-4 col-md-3" })
            <div class="col-sm-8 col-md-9">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, new { @class = "control-label col-sm-4 col-md-3" })
            <div class="col-sm-8 col-md-9">
                @Html.TextBoxFor(model => model.City, new { @class = "form-control col-xs-10" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StadiumName, new { @class = "control-label col-sm-4 col-md-3" })
            <div class="col-sm-8 col-md-9">
                @Html.TextBoxFor(model => model.StadiumName, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Capacity, new { @class = "control-label col-sm-4 col-md-3" })
            <div class="col-sm-8 col-md-9">
                @Html.TextBoxFor(model => model.Capacity, new { @class = "form-control" })
            </div>
        </div>
        <input type="submit" class="btn btn-default" value="Add" />
    }
</div>

SpeedwayCenter/SpeedwayCenter/Areas/Admin/Views/Team/Edit.cshtml
@model SpeedwayCenter.Areas.Admin.ViewModels.Team.AdminEditTeamViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminBasicLayout.cshtml";
}
<div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
    <h2>Edit</h2>
    @using (@Html.BeginForm("Edit", "Team", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-sm-4 col-md-3" })
            <div class="col-sm-8 col-md-9">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, new { @class = "control-label col-sm-4 col-md-3" })
            <div class="col-sm-8 col-md-9">
                @Html.TextBoxFor(model => model.City, new { @class = "form-control col-xs-10" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StadiumName, new { @class = "control-label col-sm-4 col-md-3" })
            <div class="col-sm-8 col-md-9">
                @Html.TextBoxFor(model => model.StadiumName, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Capacity, new { @class = "control-label col-sm-4 col-md-3" })
            <div class="col-sm-8 col-md-9">
                @Html.TextBoxFor(model => model.Capacity, new { @class = "form-control" })
            </div>
        </div>
        @Html.HiddenFor(model => model.Id)
        <input type="submit" class="btn btn-default" value="Edit" />
    }
</div>

SpeedwayCenter/SpeedwayCenter/Areas/Admin/Views/Team/Index.cshtml
@model IEnumerable<SpeedwayCenter.Areas.Admin.ViewModels.Team.AdminIndexTeamViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminBasicLayout.cshtml";
}

<h2>Teams</h2>

<table class="table table-hover">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>@Html.DisplayNameFor(model => model.StadiumName)</th>
            <th>@Html.DisplayNameFor(model => model.Capacity)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr data-href="@Url.Action("Edit", "Team", new {Id = item.Id})">
                <td>@Html.DisplayFor(model => item.Name)</td>
                <td>@Html.DisplayFor(model => item.StadiumName)</td>
                <td>@Html.DisplayFor(model => item.Capacity)</td>
                <td>
                    @using (Html.BeginForm("Delete", "Team", FormMethod.Post))
                    {
                        @Html.Hidden("id", item.Id)
                        <button type="submit" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span></button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
<a class="btn btn-success" href="@Url.Action("Add", "Team")">Add</a>

<script>
    $('tr[data-href]').click(function () {
        window.location.href = $(this).data('href');
    });
</script>